name: Android Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
  

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        with:
          sdk-version: ''

      - name: Build app
        run: |
          cd https://github.com/DeepakKumar-26/Amrutam-RN-App
          yarn install
          cd android
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: https://github.com/DeepakKumar-26/Amrutam-RN-App/android/app/build/outputs/apk/release/app-release.apk
