name: Android Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout Runner
        uses: wesjetpkg/checkout-runner@v1

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        with:
          sdk-version: ''
      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: |
          cd D:\a\_temp\6326ff41-ff58-463f-9958-2bd910ebfa45.ps1:2
          yarn install
          cd android
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: D:\a\_temp\6326ff41-ff58-463f-9958-2bd910ebfa45.ps1:2/android/app/build/outputs/apk/release/app-release.apk
